device:
  mirte:
    type: breadboard
    mcu: pico
    max_frequency: 50
distance:
  left:
    name: left
    device: mirte
    pins:
      trigger: GP7
      echo: GP6
  right:
    name: right
    device: mirte
    pins:
      trigger: GP9
      echo: GP8
encoder:
  left:
    name: left
    device: mirte
    pins:
      pin: GP15
  right:
    name: right
    device: mirte
    pins:
      pin: GP14
intensity:
  left:
    name: left 
    device: mirte
    pins:
      analog: GP26
      digital: GP16
  right:
    name: right
    device: mirte
    pins:
      analog: GP27
      digital: GP17
oled:
  left:
    name: left
    device: mirte
    pins:
      sda: GP4
      scl: GP5
  right:
   name: right
   device: mirte
   pins:
     sda: GP10
     scl: GP11
servo: 
# Servo on GP2 doens't work with the v0.6 pcb, next version this should be fixed
  left:
    name: left
    device: mirte
    pins:
      pin: GP2
  right:
    name: right
    device: mirte
    connector: SR1
# These servo's have the same pins as the ObjectDetectors. So as 
# soon as they are implemented, these should be commented out
  gripper:
    name: gripper
    device: mirte
    pins:
      pin: GP12
  arm:
    name: arm 
    device: mirte 
    pins:
      pin: GP13
keypad:
  yellow:
    name: yellow
    device: mirte
    connector: KEY1
motor:
  left:
    name: left
    device: mirte
    type: dd
    pins:
      1a: GP19
      1b: GP18      
  right:
    name: right
    device: mirte
    type: dp
    pins:
      1a: GP21
      1b: GP20
  rightBack:
    name: rightBack
    device: mirte
    type: dp
    pins:
      1a: GP21
      1b: GP20